### ISSUE TITLE
add single config file

### ISSUE THREAD

**Issue by sthoduka** [sthoduka/kortex_vision#2]
Currently configuration parameters are in the launch files and camera calibration parameters are in .ini files. A single JSON file with all configuration and calibration parameters would be preferable.

Some important config parameters are:
* device IP address
* static transform between RGB and depth cameras
* RTSP urls for color and depth

**Comment by sthoduka** [comment]
Also add some sample code to load the config file. We can add a dependency to [jsoncpp](https://github.com/open-source-parsers/jsoncpp) (`sudo apt install libjsoncpp1`).

**Comment by lscarton** [comment]
@sthoduka the first draft of the json config file is ready for revision.
It seems to me that the `RTSP urls` require  to use system variables, i have therefore put `TODO` as place holder.

**Comment by sthoduka** [comment]
which system variables?

**Comment by sthoduka** [comment]
looks good to me. Instead of the full URL, we just need to have a key-value pair for "color" and "depth" and we can construct the URL in the code as "rtsp://<config.device_ip>/<config.rtsp_stream_location>"
